In [1]:
import numpy as np

In [2]:
escañar = 5.697
vector = np.array([1,2,3,4])
matriz = np.array([[1,2],[3,4],[5,6]])
tensor = np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
    [[11,12,13],[14,15,16],[17,18,19]],
    [[21,22,23],[24,25,26],[27,28,29]],
])

In [3]:
escañar_t = escañar.T

AttributeError: 'float' object has no attribute 'T'

In [5]:
vector_t = vector.T
print(vector_t)

[1 2 3 4]


In [7]:
matriz_t = matriz.T
print(matriz_t)

[[1 3 5]
 [2 4 6]]


In [8]:
tensor_t = tensor.T
print(tensor_t)

[[[ 1 11 21]
  [ 4 14 24]
  [ 7 17 27]]

 [[ 2 12 22]
  [ 5 15 25]
  [ 8 18 28]]

 [[ 3 13 23]
  [ 6 16 26]
  [ 9 19 29]]]


In [9]:
print(tensor)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [10]:
print(tensor.shape)

(3, 3, 3)


In [11]:
A = matriz
B = matriz_t

In [12]:
C = A + B

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [13]:
A = np.array([[1,2],[3,4],[5,6]]) #2,3

In [14]:
B = np.array([[6,5],[4,3],[2,1]]) #2,3

In [15]:
C = A + B 
print(A)
print(B)
print(C) #2,3

[[1 2]
 [3 4]
 [4 5]]
[[6 5]
 [4 3]
 [2 1]]
[[7 7]
 [7 7]
 [6 6]]


In [18]:
D = matriz + escañar
print(D) #a cada elemento se le suma el valor de vector

[[ 6.697  7.697]
 [ 8.697  9.697]
 [10.697 11.697]]
