In [1]:
import numpy as np

In [25]:
# matriz_A = np.array([[1,2,-3], [2,5,-8], [-3,-6,9]], np.int32)
# matriz_B = np.array([[1], [4] ,[-3]], np.int32)
# print(matriz_A.shape)
# print(matriz_B.shape)

(3, 3)
(3, 1)


In [27]:
# print(np.linalg.det(matriz_A))
# if (np.linalg.det(matriz_A)) != 0.0:
#     print("Matriz Inversa")
#     inv_A = np.linalg.inv(matriz_A)
#     print(inv_A)
#     print("Multiplicacion")
#     print(np.dot(inv_A , matriz_B) )
#     print(inv_A.dtype)
# else:
#         print("la matriz es singular")

In [45]:
matriz_A = np.array([[1, 2, -3], [2, 5, -8], [-3, -6, 9]])
print(matriz_A)
matriz_B = np.array([1, 4, -3])
print(matriz_B)

[[ 1  2 -3]
 [ 2  5 -8]
 [-3 -6  9]]
[ 1  4 -3]


In [46]:
x = np.linalg.solve(matriz_A, matriz_B)
print(x)

[-2.96059473e-16 -4.00000000e+00 -3.00000000e+00]


In [47]:
matriz_A @ x == matriz_B 

array([False,  True,  True])